import { QueryInterface } from 'sequelize';

export default {
  up: async (queryInterface: QueryInterface) => {
    await queryInterface.bulkInsert('sellers',
    [
      {
        full_name: 'João da Silva',
        password: '12QFr&6',
        birthday: '1993-03-03',
        cpf: '88878542309',
        nacionality: 'Brasileiro',
        gender: 'Masculino',
        phone_number: '(32)878522319',
        email: 'js@milomotors.com.br',
        bank: 'Santander',
        sales_quantity: 0,
        job_occupation: 'Vendedor',
        commission: 0,
        address_id: 11,
      },
      {
        full_name: 'Mariana Albuquerque',
        password: '123aB#cd',
        birthday: '1990-01-01',
        cpf: '01212345678',
        nacionality: 'Brasileira',
        gender: 'Feminino',
        phone_number: '(32)987654321',
        email: 'ma@milomotors.com.br',
        sales_quantity: 3,
        job_occupation: 'Vendedor',
        commission: 12000.00,
        address_id: 12,
      },
      {
        full_name: 'Fernanda Oliveira',
        password: 'fuinR#rua123',
        birthday: '1992-02-02',
        cpf: '02345678901',
        nacionality: 'Brasileiro',
        gender: 'Feminino',
        phone_number: '(32)881245789',
        email: 'fo@milomotors.com.br',
        bank: 'Banco do Brasil',
        sales_quantity: 1,
        job_occupation: 'Vendedor',
        commission: 3500.00,
        address_id: 13,
      },
      {
        full_name: 'Mateus Vieira Júnior',
        password: 'batatA@123',
        birthday: '1995-07-07',
        cpf: '99988877766',
        nacionality: 'Brasileiro',
        gender: 'Masculino',
        phone_number: '(32)999752412',
        email: 'mvj@milomotors.com.br',
        sales_quantity: 8,
        job_occupation: 'Vendedor',
        commission: 22750.00,
        address_id: 14,
      },
      {
        full_name: 'Tamires da Rosa Almeida',
        password: 'roSa#%123',
        birthday: '1995-07-07',
        cpf: '55877844201',
        nacionality: 'Brasileiro',
        gender: 'Feminino',
        phone_number: '(32)789456001',
        email: 'tra@milomotors.com.br',
        bank: 'Santander',
        sales_quantity: 5,
        job_occupation: 'Vendedor',
        commission: 14250.00,
        address_id: 15,
      },
      {
        full_name: 'Rafaela da Silva',
        password: 'Rafa@123',
        birthday: '1995-07-07',
        cpf: '03398765432',
        nacionality: 'Brasileira',
        gender: 'Feminino',
        phone_number: '(32)999888777',
        email: 'rafa@milomotors.com.br',
        bank: 'Bradesco',
        sales_quantity: 0,
        job_occupation: 'Gerente',
        commission: 0,
        address_id: 16,
      },
    ], {});
  },

  down: async (queryInterface: QueryInterface) => {
    await queryInterface.bulkDelete('sellers', {});
  }
};
